# 项目相关配置
xiaogu:
  # 名称
  name: XiaoGu
  # 版本
  version: 3.8.7
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/xiaogu/uploadPath，Linux配置 /home/xiaogu/uploadPath）
  profile: E:\\xiaogutmp
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.atguigu: debug
    org.springframework: warn
    # 关闭ChatResponseMetadata的调试日志
    org.springframework.ai.chat.metadata: warn  # 添加这一行
    org.springframework.ai.chat: TRACE  # 添加这一行
    org.springframework.ai: debug # AI对话的日志级别
    com.itheima.ai: debug # 本项目的日志级别

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
    include: mongodb
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  data:
    redis:
      # 地址
      host: 192.168.223.134
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 密码
      password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
  ai:
    openai: #openai配置
      # openai: gpt-3.5-turbo gpt-4o
      #      base-url: https://api.xty.app #api中转地址
      base-url: https://dashscope.aliyuncs.com/compatible-mode #阿里百炼api地址
      #      api-key: ${OPENAI_API_KEY}
      api-key: ${ALIYUN_API_KEY} #读取环境变量中的阿里百炼 api key
      chat:
        options:
          model: qwen-turbo
          max-tokens: 2000
      embedding:
        options:
          model: text-embedding-v4 #如果要使用阿里云百炼,一定要手动配置这个embedding的model
    ollama:
      # ollama config: deepseek-r1:1.5b  llama3:latest
      base-url: http://localhost:11434
      embedding:
        model: qwen2.5:1.5b
      chat:
        model: qwen2.5:1.5b
        options:
          temperature: 0.2  # 降低温度值抑制随机性
          top-p: 0.2        # 控制多样性
#          repeat_penalty: 1.5  # 添加重复惩罚系数
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        initialize-schema: true

    mcp:
      client:
        enabled: true
        name: amap-mcp-client
        version: 1.0.0
        request-timeout: 180s  # 增加到3分钟
        type: SYNC
        toolcallback:
          enabled: true
        sse:
          connections:
            amap:
              url: https://mcp.amap.com
              sse-endpoint: /sse?key=${AMAP_API_KEY}
              read-timeout: 180s      # 增加读取超时
              connect-timeout: 90s   # 增加连接超时

  #  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/itheima?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
#    username: root
#    password: 123456
  main:
    allow-bean-definition-overriding: true
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.atguigu.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api
# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
springdoc:
  group-configs:
    - group: default
      paths-to-match: /ai/**, /chat/**
