logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

spring:
  ai:
    ollama:
      embedding:
        dimensions: 3584 # ollama嵌入向量维度
